# main text of home
name: Luke Metz
bio: AI research & product

# twitter summary info
description: description?

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/me2.jpeg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

publications: true

url: https://lukemetz.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-112984812-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 21

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: lukemetz-com
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: Luke_Metz
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: luke-metz-5003046a
# youtube: myyoutube
# spotify: myspotify
github: lukemetz
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: luke.s.metz@gmail.com

authors:
    lukemetz:
        name: Luke Metz
        # bio: A Man who travels the world eating noodles
        external-image: false
        picture: assets/images/me2.jpeg
        twitter: Luke_Metz

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
publications: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
#- jemoji

jekyll-mentions:
    base_url: https://github.com

publications_list:

  - year_split: true
    year: 2023
  
  - title: "Gpt-4 technical report"
    people: OpenAI
    arxiv: https://arxiv.org/pdf/2303.08774

  - title: "Variance-reduced gradient estimation via noise-reuse in online evolution strategies"
    people: 
      - Oscar Li
      - James Harrison
      - Jascha Sohl-Dickstein
      - Virginia Smith
      - Luke Metz
    location: NeurIPS 2023
    arxiv: https://arxiv.org/abs/2304.12180

  - title: "Transformer-based learned optimization"
    people: 
      - Erik Gärtner
      - Luke Metz
      - Mykhaylo Andriluka
      - C Daniel Freeman
      - Cristian Sminchisescu
    location: IEEE/CVF Conference on Computer Vision and Pattern Recognition
    arxiv: "https://openaccess.thecvf.com/content/CVPR2023/papers/Gartner_Transformer-Based_Learned_Optimization_CVPR_2023_paper.pdf"

  - year_split: true
    year: 2022

  - title: "ChatGPT: Optimizing language models for dialogue (blog post)"
    people: OpenAI
    arxiv: https://openai.com/index/chatgpt/

  - title: "Velo: Training versatile learned optimizers by scaling up"
    people:
      - Luke Metz
      - James Harrison
      - C Daniel Freeman
      - Amil Merchant
      - Lucas Beyer
      - James Bradbury
      - Naman Agrawal
      - Ben Poole
      - Igor Mordatch
      - Adam Roberts
      - Jascha Sohl-Dickstein
    arxiv: "https://arxiv.org/abs/2211.09760"

  - title: "Beyond the imitation game: Quantifying and extrapolating the capabilities of language models"
    people:
      - "[Many people!]"
    arxiv: https://arxiv.org/abs/2206.04615
    

  - title: "Lyapunov Exponents for Diversity in Differentiable Games"
    people:
        - Jonathan Lorraine
        - Paul Vicol
        - Jack Parker-Holder
        - Tal Kachman
        - Luke Metz
        - Jakob Foerster
    location: AAMAS 2022
    arxiv: https://arxiv.org/pdf/2112.14570.pdf


  - title: "General-purpose in-context learning by meta-learning transformers"
    people:
      - Louis Kirsch
      - James Harrison
      - Jascha Sohl-Dickstein
      - Luke Metz
    arxiv: https://arxiv.org/pdf/2212.04458

  - title: "A closer look at learned optimization: Stability, robustness, and inductive biases"
    people: 
      - James Harrison
      - Luke Metz
      - Jascha Sohl-Dickstein
    location: NeurIPS 2022
    arxiv: "https://proceedings.neurips.cc/paper_files/paper/2022/file/184c1e18d00d7752805324da48ad25be-Paper-Conference.pdf"
  
  - title: "Discovered policy optimisation"
    people: 
      - Chris Lu
      - Jakub Kuba
      - Alistair Letcher
      - Luke Metz
      - Christian Schroeder de Witt
      - Jakob Foerster
    location: NeurIPS 2022
    arxiv: "https://proceedings.neurips.cc/paper_files/paper/2022/file/688c7a82e31653e7c256c6c29fd3b438-Paper-Conference.pdf"

  - title: "Practical tradeoffs between memory, compute, and performance in learned optimizers"
    people: 
      - Luke Metz
      - C Daniel Freeman
      - James Harrison
      - Niru Maheswaranathan
      - Jascha Sohl-Dickstein
    location: Conference on Lifelong Learning Agents, 2022
    arxiv: https://proceedings.mlr.press/v199/metz22a/metz22a.pdf


  - year_split: true
    year: 2021

  - title: "Gradients are Not All You Need"
    people:
        - Luke Metz*
        - C Daniel Freeman*
        - Samuel S Schoenholz
        - Tal Kachman
    arxiv: https://arxiv.org/pdf/2111.05803.pdf
        
  
  - title: "Unbiased Gradient Estimation in Unrolled Computation Graphs with Persistent Evolution Strategies"
    people:
        - Paul Vicol
        - Luke Metz
        - Jascha Sohl-Dickstein
    location: ICML 2021, Best paper award
    arxiv: https://arxiv.org/pdf/2112.13835.pdf

  - title: "Learn2Hop: Learned Optimization on Rough Landscapes"
    people:
        - Amil Merchant
        - Luke Metz
        - Samuel S Schoenholz
        - Ekin D Cubuk
    location: ICML 2021
    arxiv: https://arxiv.org/pdf/2107.09661.pdf

  - title: "On linear identifiability of learned representations"
    people:
      - Geoffrey Roeder
      - Luke Metz
      - Diederik P. Kingma
    location: ICML 2021, DeepMath Workshop 2019
    arxiv: https://arxiv.org/pdf/2007.00810.pdf

  - title: "Training Learned Optimizers with Randomly Initialized Learned Optimizers"
    people: 
        - Luke Metz
        - C. Daniel Freeman
        - Niru Maheswaranathan
        - Jascha Sohl-Dickstein
    arxiv: https://arxiv.org/pdf/2101.07367

  - title: "Reverse engineering learned optimizers reveals known and novel mechanisms"
    people:
      - Niru Maheswaranathan
      - David Sussillo
      - Luke Metz
      - Ruoxi Sun
      - Jascha Sohl-Dickstein
    location: NeurIPS 2021. NeurIPS MetaLearning Workshop 2020
    arxiv: https://arxiv.org/pdf/2011.02159.pdf

  - year_split: true
    year: 2020

  - title: "Parallel training of deep networks with local updates"
    people:
        - Michael Laskin*
        - Luke Metz*
        - Seth Nabarrao
        - Mark Saroufim
        - Badreddine Noune
        - Carlo Luschi
        - Jascha Sohl-Dickstein
        - Pieter Abbeel
    arxiv: https://arxiv.org/pdf/2012.03837.pdf


  - title: "Ridge Rider: Finding Diverse Solutions by Following Eigenvectors of the Hessian"
    people:
      - Jack Parker-Holder*
      - Luke Metz
      - Cinjon Resnick
      - Hengyuan Hu
      - Adam Lerer
      - Alistair Letcher
      - Alexander Peysakhovich
      - Aldo Pacchiano
      - Jakob Foerster*
    location: NeurIPS 2020
    arxiv: https://proceedings.neurips.cc/paper/2020/file/08425b881bcde94a383cd258cea331be-Paper.pdf

  
  - title: "Tasks, stability, architecture, and compute: Training more effective learned optimizers, and using them to train themselves"
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - C Daniel Freeman
      - Ben Poole
      - Jascha Sohl-Dickstein
    location: NeurIPS MetaLearning Workshop 2020
    arxiv: https://arxiv.org/pdf/2009.11243.pdf

  - title: "Using a thousand optimization tasks to learn hyperparameter search strategies"
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - Ruoxi Sun
      - C Daniel Freeman
      - Ben Poole
      - Jascha Sohl-Dickstein
    location: NeurIPS MetaLearning Workshop 2020
    arxiv: https://arxiv.org/pdf/2002.11887.pdf



  - year_split: true
    year: 2019


  - title: "Learning to Predict Without Looking Ahead: World Models Without Forward Prediction"
    people:
      - C. Daniel Freeman
      - Luke Metz
      - David Ha
    location: NeurIPS 2019
    arxiv: https://arxiv.org/pdf/1910.13038.pdf


  - title: Understanding and correcting pathologies in the training of learned optimizers
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - Jeremy Nixon
      - C. Daniel Freeman
      - Jascha Sohl-Dickstein
    location: ICML 2019 (20 min oral), NeurIPS 2018 metalearning workshop
    arxiv: https://arxiv.org/pdf/1810.10180.pdf


  - title: "Guided evolutionary strategies: Augmenting random search with surrogate gradients"
    people:
      - Niru Maheswaranathan
      - Luke Metz
      - George Tucker
      - Jascha Sohl-Dickstein
    location: ICML 2019
    arxiv: https://arxiv.org/pdf/1806.10230.pdf

  - title: Meta-Learning Update Rules for Unsupervised Representation Learning
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - Brian Cheung
      - Jascha Sohl-Dickstein
    arxiv: https://arxiv.org/pdf/1804.00222.pdf
    location: ICLR 2019 (oral), COSYNE 2018 (oral), NeurIPS 2017 metalearning workshop


  - title: Towards GAN Benchmarks Which Require Generalization 
    people:
      - Ishaan Gulrajani 
      - Colin Raffel
      - Luke Metz
    location: ICLR 2019
    arxiv: https://openreview.net/pdf?id=HkxKH2AcFm


  - title: Using learned optimizers to make models robust to input noise
    people:
      - Luke Metz
      - Niru Maheswaranathan
      - Jonathon Shlens
      - Jascha Sohl-Dickstein
      - Ekin D. Cubuk
    location: "ICML workshop: Uncertainty and Robustness in Deep Learning 2019"
    arxiv: https://arxiv.org/pdf/1906.03367.pdf


  - year_split: true
    year: 2018


  - title: Adversarial Spheres
    people:
      - Justin Gilmer
      - Luke Metz
      - Fartash Faghri
      - Samuel S Schoenholz
      - Maithra Raghu
      - Martin Wattenberg
      - Ian Goodfellow
    arxiv: https://arxiv.org/pdf/1801.02774

  - year_split: true
    year: 2017

  - title: Compositional Pattern Producing GAN
    people:
      - Luke Metz
      - Ishaan Gulrajani
    arxiv: https://nips2017creativity.github.io/doc/CPPNGAN.pdf
    location: NeurIPS 2017 creativity workshop

  - title: Discrete Sequential Prediction of Continuous Actions for Deep RL
    people:
      - Luke Metz
      - Julian Ibarz
      - Navdeep Jaitly
      - James Davidson
    arxiv: https://arxiv.org/pdf/1705.05035

  - title: "Began: Boundary Equilibrium Generative Adversarial Networks"
    people:
      - David Berthelot
      - Tom Schumm
      - Luke Metz
    arxiv: https://arxiv.org/pdf/1703.10717

  - title: Unrolled Generative Adversarial Networks
    people:
      - Luke Metz
      - Ben Poole
      - David Pfau
      - Jascha Sohl-Dickstein
    location: ICLR 2017
    arxiv: https://arxiv.org/abs/1611.02163

  - year_split: true
    year: 2016
  - title: Unsupervised Representation Learning With Deep Convolutional Generative Adversarial Networks
    people:
      - Alec Radford
      - Luke Metz
      - Soumith Chintala
    location: ICLR 2016
    arxiv: https://arxiv.org/abs/1511.06434
